### ISSUE TITLE
Remove dependency to pdo_dblib

### ISSUE THREAD

**Issue by mwaldmueller** [Thomas-Gelf/icingaweb2-module-eventtracker#29]
pdo_dblib requires freetds as depencendency. On current operatingsystems (e.g. SLES 15 SP3) neither pdo_dblib nor freetds is available via packages.

# Environment
Eventtracker: v0.9.0
PHP: 7.4.6

**Comment by Thomas-Gelf** [comment]
Hi @mwaldmueller,

thanks for reporting this. Do you have any clue why (and since when) freetds is missing? Seems that they're shipping at least related debug packages:

https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=15.4&arch=x86_64&query=freetds&module=

Weird. Please note that FreeTDS is still very active and ships many [releases](https://github.com/FreeTDS/freetds/tags). Apart from this, our underlying library should accept pdo_dblib, pdo_mssql and pdo_sybase - as soon as you manage it to get an MSSQL connection configured in Icinga Web, it should work
